spring:
  application:
    name: spring-boot-discovery-server


server:
  port: ${PORT:8761}

eureka:
  instance:
    hostname: ${EURKEKA_HOST:localhost}
  client:
    registerWithEureka: false
    fetchRegistry: false

